within VPPth.Components;

model TemperatureSource "Temperature source"
  extends Interfaces.TemperatureSource;
  annotation(
    Icon(graphics = {Text(origin = {0, 66}, fillColor = {255, 255, 255}, fillPattern = FillPattern.Solid, extent = {{-120, -110}, {120, -150}}, textString = "fixed temperature"), Rectangle(origin = {20, -21}, pattern = LinePattern.Dot, extent = {{-74, 79}, {26, -17}}), Polygon(origin = {-20, 74}, lineColor = {191, 0, 0}, fillColor = {191, 0, 0}, fillPattern = FillPattern.Vertical, points = {{4, -56}, {-8, -74}, {0, -90}, {16, -94}, {30, -92}, {38, -74}, {30, -62}, {22, -50}, {30, -26}, {10, -50}, {8, -52}, {6, -56}, {14, -54}, {18, -66}, {14, -76}, {0, -76}, {4, -58}, {4, -56}}, smooth = Smooth.Bezier), Polygon(origin = {-12, 60}, lineColor = {191, 0, 0}, fillColor = {255, 255, 255}, fillPattern = FillPattern.Solid, points = {{10, -66}, {6, -66}, {0, -66}, {4, -70}, {10, -72}, {16, -72}, {20, -68}, {20, -62}, {18, -58}, {14, -52}, {14, -60}, {14, -62}, {12, -64}, {10, -66}}, smooth = Smooth.Bezier)}, coordinateSystem(extent = {{-100, -100}, {100, 110}}, initialScale = 0.1)),
    Diagram(coordinateSystem(extent = {{-100, -100}, {100, 110}})),
    Documentation(info = "<html><head></head><body><div><font size=\"5\"><b><br></b></font></div><div><font size=\"5\"><b>Combined Heat and Power (CHP)</b></font></div><div><font size=\"4\"><br></font></div><div><font size=\"4\">The combined heat and power component (CHP) contributes both heat and power simultaneously to the respective system. The relation of this two particular types of energy is dynamically optimized under consideration of current fuel and electricity prices. However, the thermal demand has priority and has to be fulfilled at any time.</font></div><div><font size=\"4\"><br></font></div><div><font size=\"4\">The CHP unit consists of a gas boiler and a steam condenser. The gas boiler is the backup for the CHP and can fully generate the required heat. By consuming gas in order to generate certain amounts of heat and power the incurring costs are considered. The steam condenser is able to consume any overproduced heat in the system.</font></div><div><font size=\"4\"><br></font></div><div><font size=\"4\">The CHP interfaces extends the generator interface by a thermal part. The optimizer monitors the alarms and, if a signal is detected, the unit will not be considered for the heat and electrical balance. The output from the model is the start/stop command for the WISAG controller. If there is no output at all (CHP turned off) the heat demand will be supplied entirely by the gas boiler and any possible thermal storage.</font></div></body></html>"));
end TemperatureSource;
